# Generated by Django 4.0.3 on 2022-03-08 06:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_status', models.CharField(choices=[('1', 'not checked'), ('2', 'confirmed'), ('3', 'not confirmed'), ('4', 'deleted')], default='1', max_length=1, verbose_name='status')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='published date')),
                ('content', models.TextField(validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='content')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('image', models.ImageField(blank=True, upload_to='posts_images/%Y/%m/%d/', verbose_name='image')),
                ('video', models.FileField(blank=True, upload_to='posts_videos/%Y/%m/%d/', verbose_name='video')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='name')),
                ('verbose_name', models.CharField(max_length=25, verbose_name='verbose name')),
                ('selling', models.BooleanField(default=False, verbose_name='selling filter')),
            ],
            options={
                'verbose_name': 'Filter',
                'verbose_name_plural': 'Filters',
            },
        ),
        migrations.CreateModel(
            name='Filter_Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, db_index=False, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Filter Attribute',
                'verbose_name_plural': 'Filter Attributes',
                'ordering': ('filterr',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_images/%Y/%m/%d/', verbose_name='image')),
                ('alt', models.CharField(blank=True, default='', max_length=55, verbose_name='alt')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Image_icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=main.models.path_selector, verbose_name='image')),
                ('alt', models.CharField(blank=True, default='', max_length=55, verbose_name='alt')),
                ('path', models.CharField(default='products', max_length=20, verbose_name='path')),
            ],
            options={
                'verbose_name': 'Image icon',
                'verbose_name_plural': 'Image icones',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('slug', models.SlugField(allow_unicode=True, db_index=False, verbose_name='slug')),
                ('meta_title', models.CharField(blank=True, default='', max_length=60, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(160)], verbose_name='meta description')),
                ('brief_description', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='brief description')),
                ('visible', models.BooleanField(default=True, verbose_name='delete')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='published date')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, db_index=False, verbose_name='slug')),
                ('meta_title', models.CharField(blank=True, default='', max_length=60, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(160)], verbose_name='meta description')),
                ('brief_description', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='brief description')),
                ('detailed_description', models.TextField(blank=True, null=True, verbose_name='detailed description')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='price')),
                ('available', models.BooleanField(db_index=True, default=False, verbose_name='available')),
                ('visible', models.BooleanField(db_index=True, default=True, verbose_name='delete')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('brand', models.CharField(blank=True, max_length=25, null=True, verbose_name='brand')),
                ('weight', models.FloatField(null=True, verbose_name='weight')),
                ('size', models.CharField(blank=True, max_length=25, null=True, verbose_name='size')),
                ('filter_attributes', models.ManyToManyField(blank=True, to='main.filter_attribute', verbose_name='filter attributes')),
                ('image_icon', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image_icon', verbose_name='image icon')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submiters', models.PositiveIntegerField(default=0, verbose_name='submiters')),
                ('rate', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='rate')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, unique=True, verbose_name='key')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10, unique=True, verbose_name='key')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='towns', to='main.state', to_field='key', verbose_name='state')),
            ],
            options={
                'verbose_name': 'Town',
                'verbose_name_plural': 'Towns',
            },
        ),
        migrations.CreateModel(
            name='SmallImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_images/%Y/%m/%d/smallimages/', verbose_name='image')),
                ('alt', models.CharField(blank=True, default='', max_length=55, verbose_name='alt')),
                ('father', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.image', verbose_name='father')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smallimages', to='main.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'SmallImage',
                'verbose_name_plural': 'SmallImages',
            },
        ),
        migrations.CreateModel(
            name='ShopFilterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stock', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(verbose_name='stock')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='price')),
                ('available', models.BooleanField(db_index=True, default=False, verbose_name='available')),
                ('filter_attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.filter_attribute', verbose_name='filter attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopfilteritems', to='main.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'shopfilteritem',
                'verbose_name_plural': 'shopfilteritems',
            },
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, db_index=False, verbose_name='slug')),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='level')),
                ('levels_afterthis', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('previous_father_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('all_childes_id', models.TextField(blank=True, default='')),
                ('post_product', models.CharField(default='product', max_length=10, verbose_name='post or product')),
                ('father_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_childs', related_query_name='childs', to='main.root', verbose_name='father root')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'ordering': ('level',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.rating', verbose_name='rating'),
        ),
        migrations.AddField(
            model_name='product',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.root', verbose_name='root'),
        ),
    ]
