# Generated by Django 4.0.3 on 2022-03-08 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_icon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image_icon', verbose_name='image icon'),
        ),
        migrations.AddField(
            model_name='post',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.root', verbose_name='root'),
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='filter_attribute',
            name='filterr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_attributes', to='main.filter', verbose_name='filter'),
        ),
        migrations.AddField(
            model_name='filter',
            name='roots',
            field=models.ManyToManyField(to='main.root', verbose_name='roots'),
        ),
        migrations.AddField(
            model_name='content',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_set_author', related_query_name='comments_author', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='confermer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_set_confermer', related_query_name='comments_confermer', to=settings.AUTH_USER_MODEL, verbose_name='confermer'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.post', verbose_name='post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='product'),
        ),
    ]
