# Generated by Django 4.0.3 on 2023-06-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, db_index=False, max_length=255, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, db_index=False, max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, db_index=False, max_length=255, null=True, verbose_name='slug'),
        ),
    ]
