# Generated by Django 4.0.3 on 2023-06-07 04:33

import customed_files.django.classes.model_fields_custom
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_icon',
        ),
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image_icon', verbose_name='main image'),
        ),
        migrations.AddField(
            model_name='post',
            name='main_image_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image_icon', verbose_name='main image'),
        ),
        migrations.AddField(
            model_name='post',
            name='main_image_fa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image_icon', verbose_name='main image'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=customed_files.django.classes.model_fields_custom.TextFieldListed(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags_en',
            field=customed_files.django.classes.model_fields_custom.TextFieldListed(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags_fa',
            field=customed_files.django.classes.model_fields_custom.TextFieldListed(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='detailed_description',
            field=models.TextField(blank=True, verbose_name='detailed description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='detailed_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='detailed description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='detailed_description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='detailed description'),
        ),
    ]
