# Generated by Django 4.0.3 on 2023-06-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_post_main_image_en_remove_post_main_image_fa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
