# Generated by Django 4.0.3 on 2022-03-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='detailed_description',
            field=models.TextField(blank=True, null=True, verbose_name='detailed description'),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
