# Generated by Django 4.0.3 on 2023-06-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_icon',
            name='alt',
            field=models.CharField(default=None, max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
        migrations.AlterField(
            model_name='image_icon',
            name='alt_en',
            field=models.CharField(default=None, max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
        migrations.AlterField(
            model_name='image_icon',
            name='alt_fa',
            field=models.CharField(default=None, max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
    ]
