# Generated by Django 4.0.3 on 2023-06-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instagram_link',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='nstagram link'),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram_link_en',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='nstagram link'),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram_link_fa',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='nstagram link'),
        ),
    ]
