# Generated by Django 4.0.3 on 2023-06-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_post_instagram_link_post_instagram_link_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='instagram_link_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='instagram_link_fa',
        ),
    ]
