# Generated by Django 4.0.3 on 2022-04-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_filter_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopfilteritem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
    ]
