# Generated by Django 4.0.3 on 2023-06-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_post_instagram_link_alter_product_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='instagram_link',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='instagram link'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_fa',
            field=models.CharField(max_length=150, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='meta title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title_en',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='meta title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title_fa',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='meta title'),
        ),
    ]
