# Generated by Django 4.0.3 on 2022-04-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_shopfilteritem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopfilteritem',
            name='previous_stock',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
