# Generated by Django 4.0.3 on 2023-06-13 08:49

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_post_tags_alter_post_title_alter_post_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_icon',
        ),
        migrations.AddField(
            model_name='image_icon',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.post', verbose_name='post'),
        ),
        migrations.AddField(
            model_name='image_icon',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt_en',
            field=models.CharField(max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt_fa',
            field=models.CharField(max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
        migrations.AlterField(
            model_name='image_icon',
            name='alt',
            field=models.CharField(max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
        migrations.AlterField(
            model_name='image_icon',
            name='alt_en',
            field=models.CharField(max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
        migrations.AlterField(
            model_name='image_icon',
            name='alt_fa',
            field=models.CharField(max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
        migrations.AlterField(
            model_name='image_icon',
            name='image',
            field=models.ImageField(upload_to=main.models.icon_path_selector, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='smallimage',
            name='alt',
            field=models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
        migrations.AlterField(
            model_name='smallimage',
            name='alt_en',
            field=models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
        migrations.AlterField(
            model_name='smallimage',
            name='alt_fa',
            field=models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
    ]
