# Generated by Django 4.0.3 on 2022-04-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_shopfilteritem_previous_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopfilteritem',
            options={'ordering': ['-product'], 'verbose_name': 'shopfilteritem', 'verbose_name_plural': 'shopfilteritems'},
        ),
        migrations.RemoveField(
            model_name='filter',
            name='selling',
        ),
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(default='', max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
        migrations.AlterField(
            model_name='image_icon',
            name='alt',
            field=models.CharField(default='', max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
    ]
