# Generated by Django 4.0.3 on 2022-04-20 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_post_image_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_icon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image_icon', verbose_name='image icon'),
        ),
    ]
