# Generated by Django 4.0.3 on 2022-04-27 03:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_post_image_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detailed_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='detailed description'),
        ),
    ]
