# Generated by Django 4.0.3 on 2022-08-23 08:57

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_post_detailed_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDetailProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('json', djongo.models.fields.JSONField()),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
