# Generated by Django 4.0.3 on 2022-12-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_mdetailproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='roots',
        ),
        migrations.AddField(
            model_name='root',
            name='brands',
            field=models.ManyToManyField(to='main.brand', verbose_name='brands'),
        ),
        migrations.AddField(
            model_name='root',
            name='filters',
            field=models.ManyToManyField(to='main.filter', verbose_name='roots'),
        ),
    ]
