# Generated by Django 4.0.3 on 2022-12-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_filter_roots_root_brands_root_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='root',
            name='brands',
            field=models.ManyToManyField(blank=True, to='main.brand', verbose_name='brands'),
        ),
        migrations.AlterField(
            model_name='root',
            name='father_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_roots', related_query_name='childs', to='main.root', verbose_name='father root'),
        ),
        migrations.AlterField(
            model_name='root',
            name='filters',
            field=models.ManyToManyField(blank=True, to='main.filter', verbose_name='filters'),
        ),
    ]
