# Generated by Django 4.0.3 on 2022-12-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_root_brands_alter_root_father_root_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filter_attributes',
            field=models.ManyToManyField(to='main.filter_attribute', verbose_name='filter attributes'),
        ),
    ]
