# Generated by Django 4.0.3 on 2023-01-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_product_filter_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filter_attributes',
            field=models.ManyToManyField(blank=True, to='main.filter_attribute', verbose_name='filter attributes'),
        ),
    ]
