# Generated by Django 4.0.3 on 2023-02-18 08:34

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_product_filter_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_fa',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, db_index=False, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, db_index=False, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='filter',
            name='name_en',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='filter',
            name='name_fa',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='filter',
            name='verbose_name_en',
            field=models.CharField(max_length=25, null=True, verbose_name='verbose name'),
        ),
        migrations.AddField(
            model_name='filter',
            name='verbose_name_fa',
            field=models.CharField(max_length=25, null=True, verbose_name='verbose name'),
        ),
        migrations.AddField(
            model_name='filter_attribute',
            name='name_en',
            field=models.CharField(max_length=25, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='filter_attribute',
            name='name_fa',
            field=models.CharField(max_length=25, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='filter_attribute',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, db_index=False, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='filter_attribute',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, db_index=False, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='image_icon',
            name='alt_en',
            field=models.CharField(default='', max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
        migrations.AddField(
            model_name='image_icon',
            name='alt_fa',
            field=models.CharField(default='', max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
        migrations.AddField(
            model_name='post',
            name='brief_description_en',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='brief description'),
        ),
        migrations.AddField(
            model_name='post',
            name='brief_description_fa',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='brief description'),
        ),
        migrations.AddField(
            model_name='post',
            name='detailed_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='detailed description'),
        ),
        migrations.AddField(
            model_name='post',
            name='detailed_description_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='detailed description'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_en',
            field=models.TextField(blank=True, default='', null=True, validators=[django.core.validators.MaxLengthValidator(160)], verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_fa',
            field=models.TextField(blank=True, default='', null=True, validators=[django.core.validators.MaxLengthValidator(160)], verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_en',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='meta title'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title_fa',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='meta title'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, db_index=False, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, db_index=False, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fa',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_en',
            field=models.BooleanField(db_index=True, default=False, verbose_name='available'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_fa',
            field=models.BooleanField(db_index=True, default=False, verbose_name='available'),
        ),
        migrations.AddField(
            model_name='product',
            name='brief_description_en',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='brief description'),
        ),
        migrations.AddField(
            model_name='product',
            name='brief_description_fa',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='brief description'),
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='detailed description'),
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_description_fa',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='detailed description'),
        ),
        migrations.AddField(
            model_name='product',
            name='filter_attributes_en',
            field=models.ManyToManyField(blank=True, null=True, to='main.filter_attribute', verbose_name='filter attributes'),
        ),
        migrations.AddField(
            model_name='product',
            name='filter_attributes_fa',
            field=models.ManyToManyField(blank=True, null=True, to='main.filter_attribute', verbose_name='filter attributes'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_icon_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image_icon', verbose_name='image icon'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_icon_fa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image_icon', verbose_name='image icon'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_en',
            field=models.TextField(blank=True, default='', null=True, validators=[django.core.validators.MaxLengthValidator(160)], verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_fa',
            field=models.TextField(blank=True, default='', null=True, validators=[django.core.validators.MaxLengthValidator(160)], verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_en',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='meta title'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title_fa',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='meta title'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fa',
            field=models.CharField(max_length=60, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_en',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_fa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_en',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='size'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_fa',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='size'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, db_index=False, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, db_index=False, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_en',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_fa',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_en',
            field=models.FloatField(null=True, verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_fa',
            field=models.FloatField(null=True, verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='root',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='root',
            name='name_fa',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='root',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, db_index=False, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='root',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, db_index=False, null=True, verbose_name='slug'),
        ),
    ]
