# Generated by Django 4.0.3 on 2023-04-06 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_image_alt_en_image_alt_fa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_icon_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_icon_fa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_fa',
        ),
    ]
