# Generated by Django 4.0.3 on 2023-04-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_product_image_icon_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_en',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_fa',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, null=True, verbose_name='price'),
        ),
    ]
