# Generated by Django 4.0.3 on 2023-05-08 23:22

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_product_price_alter_product_price_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('name_fa', models.CharField(max_length=50, null=True, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=50, null=True, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, db_index=False, verbose_name='slug')),
                ('slug_fa', models.SlugField(allow_unicode=True, db_index=False, null=True, verbose_name='slug')),
                ('slug_en', models.SlugField(allow_unicode=True, db_index=False, null=True, verbose_name='slug')),
                ('level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='level')),
                ('levels_afterthis', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('previous_father_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('all_childes_id', models.TextField(blank=True, default='')),
                ('post_product', models.CharField(default='product', max_length=10, verbose_name='post or product')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('level',),
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='root',
        ),
        migrations.RemoveField(
            model_name='product',
            name='root',
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, db_index=False, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, db_index=False, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, db_index=False, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='detailed_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='detailed description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='detailed_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='detailed description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='size'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.DecimalField(decimal_places=1, default='0', max_digits=2, verbose_name='rate'),
        ),
        migrations.DeleteModel(
            name='Root',
        ),
        migrations.AddField(
            model_name='category',
            name='brands',
            field=models.ManyToManyField(blank=True, to='main.brand', verbose_name='brands'),
        ),
        migrations.AddField(
            model_name='category',
            name='father_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', related_query_name='childs', to='main.category', verbose_name='father category'),
        ),
        migrations.AddField(
            model_name='category',
            name='filters',
            field=models.ManyToManyField(blank=True, to='main.filter', verbose_name='filters'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='category'),
        ),
    ]
