# Generated by Django 5.0.6 on 2024-06-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_reply_options_reply_author_reply_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesizes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
