# Generated by Django 4.0.3 on 2023-06-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, db_index=False, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, db_index=False, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, db_index=False, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='visible',
            field=models.BooleanField(db_index=True, default=True, verbose_name='visible'),
        ),
    ]
