# Generated by Django 4.0.3 on 2023-07-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.CharField(default='products', max_length=20, verbose_name='path'),
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.post', verbose_name='post'),
        ),
        migrations.CreateModel(
            name='ImageSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=55, null=True, unique=True, verbose_name='alt')),
                ('size', models.CharField(max_length=20, verbose_name='size')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesizes', to='main.image', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Image size',
                'verbose_name_plural': 'Images sizes',
            },
        ),
    ]
