# Generated by Django 4.0.3 on 2023-07-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_imagesizes_father_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesizes',
            name='alt_en',
            field=models.CharField(max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
        migrations.AddField(
            model_name='imagesizes',
            name='alt_fa',
            field=models.CharField(max_length=55, null=True, unique=True, verbose_name='alt'),
        ),
    ]
