# Generated by Django 4.1.13 on 2023-12-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_filter_genre_filter_symbole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='genre',
            field=models.CharField(choices=[('attribute', 'attribute'), ('filter', 'filter'), ('both', 'both')], max_length=25, verbose_name='genre'),
        ),
    ]
