# Generated by Django 4.1.13 on 2023-12-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_filter_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='filter_attributes_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='filter_attributes_fa',
        ),
        migrations.AlterField(
            model_name='filter_attribute',
            name='symbole_value',
            field=models.CharField(blank=True, max_length=255, verbose_name='symbole value'),
        ),
    ]
