# Generated by Django 4.0.3 on 2024-01-27 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_image_post_alter_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brief_description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='brief description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brief_description_en',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='brief description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brief_description_fa',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='brief description'),
        ),
    ]
