# Generated by Django 4.0.3 on 2023-06-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SesKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ses_key', models.CharField(blank=True, default='', max_length=60, verbose_name='ses key')),
            ],
            options={
                'verbose_name': 'ses key',
                'verbose_name_plural': 'ses keys',
            },
        ),
    ]
