# Generated by Django 4.0.3 on 2023-06-15 11:33

from django.db import migrations, models
import django.db.models.deletion
import orders.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='shipping price')),
                ('delivery_date_delay', models.CharField(max_length=30, verbose_name='delivery date delay')),
            ],
            options={
                'verbose_name': 'Personal Dispatch',
                'verbose_name_plural': 'Personal Dispatch',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_type', models.CharField(choices=[('online', 'online payment'), ('cod', 'cash on delivery')], max_length=10, verbose_name='paid type')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('cd_peigiry', models.CharField(blank=True, max_length=30, null=True, verbose_name='cd peigiry')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='price')),
                ('shipping_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='shipping price')),
                ('shipping_type', models.CharField(max_length=20, verbose_name='shipping type')),
                ('order_status', models.CharField(choices=[('0', 'in processing'), ('1', 'delivered to post/courier'), ('2', 'delivered'), ('3', 'returned'), ('4', 'canceled')], max_length=1, verbose_name='order status')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='delivery date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('visible', models.BooleanField(db_index=True, default=True, verbose_name='delete')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='price')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('visible', models.BooleanField(db_index=True, default=True, verbose_name='delete')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='personal fee')),
                ('address', models.CharField(max_length=250, verbose_name='address')),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.town', to_field='key', verbose_name='town')),
            ],
            options={
                'verbose_name': 'shipping',
                'verbose_name_plural': 'shipping',
            },
        ),
        migrations.CreateModel(
            name='ProfileOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone number')),
                ('address', models.CharField(max_length=250, verbose_name='address')),
                ('postal_code', models.CharField(max_length=10, validators=[orders.models.validate_postal_code], verbose_name='postal code')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('main', models.BooleanField(default=False, verbose_name='main profileorder')),
                ('visible', models.BooleanField(db_index=True, default=True, verbose_name='delete')),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.town', to_field='key', verbose_name='town')),
            ],
            options={
                'verbose_name': 'profile order',
                'verbose_name_plural': 'profile orders',
            },
        ),
    ]
